package com.opentok.otc;

/* loaded from: classes.dex */
public interface f {
    public static final String A;
    public static final String B;
    public static final String C;
    public static final String D;
    public static final String E;
    public static final String F;
    public static final String G;
    public static final String H;
    public static final String I;
    public static final String J;
    public static final String K;
    public static final String L;
    public static final String M;
    public static final String N;
    public static final String O;
    public static final String P;
    public static final String Q;
    public static final String R;
    public static final String S;
    public static final String T;
    public static final String U;
    public static final String V;
    public static final String W;
    public static final String X;
    public static final String Y;
    public static final String Z;
    public static final String a;
    public static final String a0;
    public static final String b;
    public static final String b0;
    public static final String c;
    public static final String d;
    public static final String e;
    public static final String f;
    public static final String g;
    public static final String h;
    public static final String i;
    public static final String j;
    public static final String k;
    public static final String l;
    public static final String m;
    public static final String n;
    public static final String o;
    public static final String p;
    public static final String q;
    public static final String r;
    public static final String s;
    public static final String t;
    public static final String u;
    public static final String v;
    public static final String w;
    public static final String x;
    public static final String y;
    public static final String z;

    static {
        opentokJNI.IS_MAC_OS_get();
        opentokJNI.IS_LINUX_get();
        opentokJNI.OTC_VIDEO_FRAME_METADATA_MAX_SIZE_get();
        a = opentokJNI.OTC_STATS_KEY_ACTIVECONNECTION_get();
        b = opentokJNI.OTC_STATS_KEY_ACTUALENCBITRATE_get();
        c = opentokJNI.OTC_STATS_KEY_AUDIOOUTPUTLEVEL_get();
        d = opentokJNI.OTC_STATS_KEY_AUDIOINPUTLEVEL_get();
        e = opentokJNI.OTC_STATS_KEY_AVAILABLERECEIVEBANDWIDTH_get();
        f = opentokJNI.OTC_STATS_KEY_AVAILABLESENDBANDWIDTH_get();
        g = opentokJNI.OTC_STATS_KEY_BUCKETDELAY_get();
        h = opentokJNI.OTC_STATS_KEY_BYTESRECEIVED_get();
        i = opentokJNI.OTC_STATS_KEY_BYTESSENT_get();
        j = opentokJNI.OTC_STATS_KEY_CHANNELID_get();
        k = opentokJNI.OTC_STATS_KEY_CODECNAME_get();
        l = opentokJNI.OTC_STATS_KEY_COMPONENT_get();
        m = opentokJNI.OTC_STATS_KEY_CONTENTNAME_get();
        n = opentokJNI.OTC_STATS_KEY_ECHOCANCELLATIONQUALITYMIN_get();
        o = opentokJNI.OTC_STATS_KEY_ECHODELAYMEDIAN_get();
        p = opentokJNI.OTC_STATS_KEY_ECHODELAYSTDDEV_get();
        q = opentokJNI.OTC_STATS_KEY_ECHORETURNLOSS_get();
        r = opentokJNI.OTC_STATS_KEY_ECHORETURNLOSSENHANCEMENT_get();
        s = opentokJNI.OTC_STATS_KEY_FIRSRECEIVED_get();
        t = opentokJNI.OTC_STATS_KEY_FIRSSENT_get();
        u = opentokJNI.OTC_STATS_KEY_FRAMEHEIGHTRECEIVED_get();
        v = opentokJNI.OTC_STATS_KEY_FRAMEHEIGHTSENT_get();
        w = opentokJNI.OTC_STATS_KEY_FRAMERATERECEIVED_get();
        x = opentokJNI.OTC_STATS_KEY_FRAMERATEDECODED_get();
        y = opentokJNI.OTC_STATS_KEY_FRAMERATEOUTPUT_get();
        z = opentokJNI.OTC_STATS_KEY_FRAMERATEINPUT_get();
        A = opentokJNI.OTC_STATS_KEY_FRAMERATESENT_get();
        B = opentokJNI.OTC_STATS_KEY_FRAMEWIDTHRECEIVED_get();
        C = opentokJNI.OTC_STATS_KEY_FRAMEWIDTHSENT_get();
        D = opentokJNI.OTC_STATS_KEY_INITIATOR_get();
        E = opentokJNI.OTC_STATS_KEY_JITTERRECEIVED_get();
        F = opentokJNI.OTC_STATS_KEY_LOCALADDRESS_get();
        G = opentokJNI.OTC_STATS_KEY_NACKSRECEIVED_get();
        H = opentokJNI.OTC_STATS_KEY_NACKSSENT_get();
        I = opentokJNI.OTC_STATS_KEY_PACKETSRECEIVED_get();
        J = opentokJNI.OTC_STATS_KEY_PACKETSSENT_get();
        K = opentokJNI.OTC_STATS_KEY_PACKETSLOST_get();
        L = opentokJNI.OTC_STATS_KEY_READABLE_get();
        M = opentokJNI.OTC_STATS_KEY_REMOTEADDRESS_get();
        N = opentokJNI.OTC_STATS_KEY_RETRANSMITBITRATE_get();
        O = opentokJNI.OTC_STATS_KEY_RTT_get();
        P = opentokJNI.OTC_STATS_KEY_TARGETENCBITRATE_get();
        Q = opentokJNI.OTC_STATS_KEY_TRANSMITBITRATE_get();
        R = opentokJNI.OTC_STATS_KEY_TRANSPORTID_get();
        S = opentokJNI.OTC_STATS_KEY_TRANSPORTTYPE_get();
        T = opentokJNI.OTC_STATS_KEY_TRACKID_get();
        U = opentokJNI.OTC_STATS_KEY_SSRC_get();
        V = opentokJNI.OTC_STATS_KEY_WRITABLE_get();
        W = opentokJNI.OTC_STATS_KEY_CANDIDATEPAIR_get();
        X = opentokJNI.OTC_STATS_KEY_LOCALCANDIDATETYPE_get();
        Y = opentokJNI.OTC_STATS_KEY_REMOTECANDIDATETYPE_get();
        Z = opentokJNI.OTC_STATS_KEY_LOCALRELAYPROTOCOL_get();
        a0 = opentokJNI.OTC_STATS_KEY_REMOTERELAYPROTOCOL_get();
        b0 = opentokJNI.OTC_STATS_KEY_LOCALCANDIDATEPRIORITY_get();
    }
}
